fix: info supports "generate" paths
Currently the info command does not support the "generate" keyword in
paths. This is a bug.

    $ chisel info --release ubuntu-24.04 base-files_chisel
    2024/10/07 08:47:57 Consulting release repository...
    2024/10/07 08:47:57 Cached ubuntu-24.04 release is still up-to-date.
    2024/10/07 08:47:57 Processing ubuntu-24.04 release...
    error: internal error: unrecognised PathInfo type: generate

This commit fixes the said bug and adds support for "generate"-kind
paths in the info command.